SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- Schema RECRUIT-ME

CREATE SCHEMA IF NOT EXISTS RECRUIT_ME
  DEFAULT CHARACTER SET utf8;

USE RECRUIT_ME;

-- Table RECRUITERS
DROP TABLE IF EXISTS RECRUITERS;
CREATE TABLE IF NOT EXISTS RECRUITERS
(
  ID          INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME  VARCHAR(25) NOT NULL,
  LAST_NAME   VARCHAR(45) NOT NULL
);

INSERT INTO RECRUITERS ( FIRST_NAME, LAST_NAME ) VALUES ( 'Anna', 'Kowalska' );

-- SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

