import {InMemoryDbService} from 'angular-in-memory-web-api';
import {User} from './users/user';

export class InMemoryDataService implements InMemoryDbService {
    createDb() {
        const users = [
            new User(1, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(2, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new User(3, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(4, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(5, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(6, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(7, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(8, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(9, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new User(10, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(11, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(12, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(13, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(14, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(15, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(16, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new User(17, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(18, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(19, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(20, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(21, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(22, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(23, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(24, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(25, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(26, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new User(27, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(28, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(29, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(20, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(21, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(22, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(23, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(24, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(25, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(26, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new User(27, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(28, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(29, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(30, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(31, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(32, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(33, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(34, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(35, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(36, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new User(37, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(38, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(39, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(40, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(41, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(42, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(43, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(44, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(45, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(46, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new User(47, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(48, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(49, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(50, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(51, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(52, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(53, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(54, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(55, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(56, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new User(57, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(58, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(59, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(60, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(61, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(62, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new User(63, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(64, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(65, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new User(66, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new User(67, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new User(68, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new User(69, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
        ];
        return {users};
    }
}
