import {InMemoryDbService} from 'angular-in-memory-web-api';
import {Recruiter} from './recruiters/recruiter';

export class InMemoryDataService implements InMemoryDbService {
    createDb() {
        const recruiters = [
            new Recruiter(1, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(2, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new Recruiter(3, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(4, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(5, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(6, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(7, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(8, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(9, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new Recruiter(10, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(11, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(12, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(13, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(14, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(15, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(16, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new Recruiter(17, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(18, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(19, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(20, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(21, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(22, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(23, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(24, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(25, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(26, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new Recruiter(27, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(28, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(29, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(20, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(21, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(22, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(23, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(24, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(25, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(26, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new Recruiter(27, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(28, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(29, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(30, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(31, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(32, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(33, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(34, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(35, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(36, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new Recruiter(37, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(38, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(39, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(40, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(41, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(42, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(43, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(44, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(45, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(46, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new Recruiter(47, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(48, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(49, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(50, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(51, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(52, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(53, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(54, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(55, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(56, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new Recruiter(57, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(58, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(59, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(60, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(61, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(62, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
            new Recruiter(63, 'bgsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(64, 'bfbske', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(65, 'bobsky', 'bob@bobmail.bob', 'Bob', 'Johnson'),
            new Recruiter(66, 'anniex', 'bob@bobmail.bob', 'Ann', 'Johnson'),
            new Recruiter(67, 'abcd', 'bob@bobmail.bob', 'John', 'Disculpe'),
            new Recruiter(68, 'dfgdfg', 'bob@bobmail.bob', 'Jerzy', 'Decapito'),
            new Recruiter(69, 'ret', 'bob@bobmail.bob', 'Vivienne', 'Cooper'),
        ];
        return {recruiters};
    }
}
